services:
  tekkit-server:
    image: ghcr.io/aj3x/tekkit-server:latest
    ports:
      - "25565:25565/udp"
      - "25565:25565/tcp"
    volumes:
      - /docker/tekkit/world:/minecraft/world
      - /docker/tekkit/server.properties:/minecraft/server.properties