services:
  tekkit-server:
    build: .
    ports:
      - "25565:25565/udp"
      - "25565:25565/tcp"
    volumes:
      - ./world:/minecraft/world
      - ./server.properties:/minecraft/server.properties